config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


root :to => 'workshops#index'

  resources :workshops
  resources :locations
  resources :sessions, :only => [:new, :create, :destroy]
  resources :users, :only => [:new, :create]
  resources :slots
  
end

app/models/location.rb
class Location < ActiveRecord::Base

  has_many :workshops

  geocoded_by :address

  validates :address, :presence => true
  validates :name, :presence => true

  after_validation :geocode
  
end

app/models/slot.rb
class Slot < ActiveRecord::Base

  has_many :workshops

  validates :time, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :workshops
  has_secure_password

  validates :name, :presence => true
  validates :email, :presence => true
  validates_uniqueness_of :email
  
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base

  belongs_to :slot
  belongs_to :user
  belongs_to :location

  validates :title, :presence => true
  validates :presenter, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def new
    @locations = Location.all
    @location = Location.new
  end

  def index
    @locations = Location.all

    respond_to do |format|
      format.html
      format.json { render :json => @locations }
    end
  end


  def create
    @location = Location.create(location_params)
    if @location.save
      flash[:notice] = "Location Added."
      redirect_to new_location_path
    else
      render 'new'
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @location }
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    flash[:alert] = "Location Deleted."
    redirect_to new_location_path
  end

  def update
    @location = Location.find(params[:id])

    if @location.update(location_params)
      flash[:notice]= "Your location has been updated."
      redirect_to locations_path
    else
      flash[:alert]= "Your location failed to update."
      render('show')
    end
  end

  private
    def location_params
      params.require(:location).permit(:address, :name)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController

  def new
    @slots = Slot.all
    @slot = Slot.new
  end

  def index
    @slots = Slot.all

    respond_to do |format|
      format.html
      format.json { render :json => @slots }
    end
  end

  def create
    @slot = Slot.create(slot_params)
    if @slot.save
      flash[:notice] = "Time Slot Added."
      redirect_to new_slot_path
    else
      render 'new'
    end
  end

  def edit
    @slot = Slot.find(params[:id])
  end

  def show
    @slot = Slot.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @slot }
    end
  end

  def destroy
    @slot = Slot.find(params[:id])
    @slot.destroy
    flash[:alert] = "time slot deleted."
    redirect_to new_slot_path
  end

  def update
    @slot = Slot.find(params[:id])

    if @slot.update(slot_params)
      flash[:notice]= "Your Time Slot has been updated."
      redirect_to slots_path
    else
      flash[:notice]= "Your time slot failed to update."
      render('show')
    end
  end

  private
    def slot_params
      params.require(:slot).permit(:time)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end

end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController

  def index
    @workshops = Workshop.all
    @workshops_grid = initialize_grid(Workshop,
      :include => [:slot],
      :order => 'id'
    )
    @locations = Location.all
    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      titles = []
      marker.lat location.latitude
      marker.lng location.longitude
      titles << "Address: " + location.address
      location.workshops.each do |workshop|
        titles << workshop.title + ' '
      end
      marker.infowindow titles.join("<br>")
    end

    respond_to do |format|
      format.html
      format.json { render :json => @workshops }
    end
  end

  def new
    @workshop = Workshop.new
    @workshops = Workshop.all
    @locations = Location.all
    @slots = Slot.all
  end

  def create
    @workshop = Workshop.create(workshop_params)
    if @workshop.save
      respond_to do |format|
        format.html do
          flash[:notice] = "Workshop created."
          redirect_to root_path
        end
        format.json { render :json => @workshop, :status => 201 }
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.json { render :json => @workshop.errors, :status => 422 }
      end
    end
  end

  def edit
    @workshop = Workshop.find(params[:id])
  end

  def show
    @workshop = Workshop.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @workshop }
    end
  end

  def destroy
    @workshop = Workshop.find(params[:id])
    @workshop.destroy
    flash[:alert] = "Workshop deleted."
    redirect_to root_url

    respond_to do |format|
      format.html do
        flash[:notice] = "Workshop deleted."
        redirect_to workshops_path
      end
      format.json { head :no_content }
    end
  end

  def update
    @workshop = Workshop.find(params[:id])
    if @workshop.update(workshop_params)
      respond_to do |format|
        format.html do
          flash[:notice] = "Workshop updated."
          redirect_to workshop_path(@workshop)
        end
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { render 'edit' }
        format.json { render :json => @workshop.errors, :status => 422 }
      end
    end
  end

  private
    def workshop_params
      params.require(:workshop).permit(:title, :presenter, :description, 
                                       :duration, :location_id, :user_id, :slot_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventPlanner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<div class="container-fluid">
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#workshop-navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Home</a>
      </div>
      <div class="collapse navbar-collapse" id="workshop-navbar">
        <ul class="nav navbar-nav">
        <% if current_user %>
          <li><a href="/workshops/new">Add Workshop</a></li>
          <li><a href="/locations/new">Add Location</a></li>
          <li><a href="/slots/new">Add Time Slot</a></li>
          <li> <%= link_to "Log Out", logout_path %></li>
        <% else %>
          <li><a href="/login">Login</a></li>
          <li><a href="/signup">Sign Up</a></li>
        <% end %>
        </ul>
      </div>
  </nav>
</div>
  <div id="notice" style="background: green; color: white; text-align:center;">
    <%= flash[:notice] %>
  </div>
  <div id="alert" style="background: red; color: white; text-align:center;">
    <%= flash[:alert] %>
  </div>
<body>
<%= yield %>
</body>
</html>

app/views/locations/_form.html.erb
<div id = 'errors'>
  <%= render('layouts/errors', :object => @location) %>
</div>
<%= form_for(@location) do |f| %>
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control" %>
      <%= f.label :address %>
      <%= f.text_field :address, :class => "form-control" %>
    </div>
  <%= f.submit(:class => "btn btn-primary") %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<%= render 'form' %>

app/views/locations/index.html.erb
<h1>Locations</h1>

<% @locations.each do |location|%>
  <p><strong><%=location.name%></strong> Address: <%=location.address%></p>
<% end %>

app/views/locations/new.html.erb
<h3>Current Locations</h3>
<div class = "rows">
  <div class="col-md-10">
    <% if @locations != nil %>
      <% @locations.each do |location| %>
        <p><%=link_to "Remove Location", location_path(location), data: {method: "delete"}, :class => "btn btn-xs btn-danger" %>
        <%= link_to "#{location.name}", edit_location_path(location) %></p>
      <% end %>
    <% end %>

  <h3> New Location </h3>
  <%= render 'form' %>
  </div>
</div>

app/views/slots/_form.html.erb
<div id = 'errors'>
  <%= render('layouts/errors', :object => @slot) %>
</div>
<%= form_for(@slot) do |f| %>
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :time %>
      <%= f.datetime_select :time, :ampm => true, :minute_step => 15, :class => "form-control" %>
    </div>
  <%= f.submit(:class => "btn btn-primary") %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<%=render 'form' %>

app/views/slots/index.html.erb
<h3> Current Time Slots </h3>

<% @slots.each do |slot| %>
  <p><%= link_to "#{slot.time}", edit_slot_path(slot) %></p>
<%end%>

<a href ='/'> Home </a>

app/views/slots/new.html.erb
<h3>Current Time Slots</h3>
<div class = "rows">
  <div class="col-md-10">
    <% @slots.each do |slot| %>
      <p><%=link_to "Remove Time Slot", slot_path(slot), data: {method: "delete"}, :class => "btn btn-xs btn-danger" %>
      <%=link_to slot.time, edit_slot_path(slot) %></p>
      
    <% end %>
  <h3> New Time Slot </h3>
  <%= render 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<h3>Sign Up</h3>

<%= form_for @user do |f| %>
  <div id="errors">
    <%= render('/layouts/errors.html', :object => @user) %>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, :autofocus => true, :class => "form-control" %>
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control" %>
      <%= f.label :password %>
      <%= f.password_field :password, :class => "form-control" %>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, :class => "form-control" %>
    </div>
    <%= f.submit "Sign Up", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/workshops/_form.html.erb
<div id = 'errors'>
  <%= render('layouts/errors', :object => @workshop) %>
</div>
<%= form_for(@workshop) do |f| %>
    <div class="form-group">
      <%= f.hidden_field :user_id, { :value => current_user.id } %>
      <%= f.label :title %>
      <%= f.text_field :title, :autofocus => true, :class => "form-control" %>
      <%= f.label :description %>
      <%= f.text_area :description, :rows => "4", :class => "form-control" %>
      <%= f.label :presenter %>
      <%= f.text_field :presenter, :class => "form-control" %>
      <%= f.label :duration %>
      <%= f.text_field :duration, :class => "form-control" %>
      <% if Location.all != nil %>
        <%= f.label :location_id %>
        <%= collection_select(:workshop, :location_id, Location.all, :id, :address, {include_blank: true}) %><br>
      <% end %>
      <% if Slot.all != nil %>
        <%= f.label :slot_id %>
        <%= collection_select(:workshop, :slot_id, Slot.all, :id, :time, {include_blank: true}) %>
      <% end %>
    </div>
      <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/workshops/_slick_sched.html.erb
<%# show_filters: :when_filtered %>
<%= grid(@workshops_grid) do |g|

  g.column name:  'Workshop Title', attribute: 'title' do |workshop|
    workshop.title
  end

  g.column  name:  'Description', attribute: 'description' do |workshop|
    workshop.description
  end

  g.column  name:  'Location' do |workshop|
    workshop.location.name if workshop.location
  end

  g.column  name:  'Time and Day' do |workshop|
    workshop.slot.time if workshop.slot
  end

  g.column  name:  'Duration' do |workshop|
    workshop.duration
  end

  g.column name:  'Presenter(s)', attribute: 'presenter' do |workshop|
    workshop.presenter
  end

  if current_user
    g.column   do |workshop|
      link_to('Edit', edit_workshop_path(workshop))
    end
  end
end -%>

app/views/workshops/edit.html.erb
<h2> Edit Workshop </h2>

<%= render 'form' %>
<br>
<p><%=link_to "Remove Workshop", workshop_path(@workshop), data: {method: "delete"}, :class => "btn btn-xs btn-danger" %></p>

app/views/workshops/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<h3>Workshops</h3>

<%= render 'slick_sched' %>

<div style='width: 800px;'>
  <div id="custom_style" style='width: 1000px; height: 600px;'></div>
</div>

<script type="text/javascript">

  var mapStyle = [{"featureType":"administrative","stylers":[{"visibility":"off"}]},{"featureType":"poi","stylers":[{"visibility":"simplified"}]},{"featureType":"road","stylers":[{"visibility":"simplified"}]},{"featureType":"water","stylers":[{"visibility":"simplified"}]},{"featureType":"transit","stylers":[{"visibility":"simplified"}]},{"featureType":"landscape","stylers":[{"visibility":"simplified"}]},{"featureType":"road.highway","stylers":[{"visibility":"off"}]},{"featureType":"road.local","stylers":[{"visibility":"on"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"visibility":"on"}]},{"featureType":"water","stylers":[{"color":"#84afa3"},{"lightness":52}]},{"stylers":[{"saturation":-77}]},{"featureType":"road"}]

  var handler = Gmaps.build('Google');
  handler.buildMap({ 
    internal: {id: 'custom_style'},
    provider: {
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      styles: mapStyle}
    }, 

  function(){
    markers = handler.addMarkers(<%=raw @hash.to_json%>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });

</script>

app/views/workshops/new.html.erb
<h3>Current Workshops</h3>
<div class = "rows">
  <div class="col-md-8">
    <% if @workshop.id != nil %>
      <% @workshops.each do |workshop| %>
        <p><%=link_to "Remove Workshop", workshop_path(workshop), data: {method: "delete"}, :class => "btn btn-xs btn-danger" %>
        <%=link_to "#{workshop.title}", edit_workshop_path(workshop) %></p>
      <% end %>
    <% end %> 
  <h3> New Workshop </h3>
  <%= render 'form' %>
  </div>
</div>

app/views/workshops/schedule.html.erb
<div class="table-responsive">
  <table class="table">
    <% Slot.all.each do |slot| %>
      <tr> <%= 
  </table>
</div>

app/views/workshops/show.html.erb
<h3>Workshop Details</h3>

<h4><%=@workshop.title%>
<p><%=@workshop.description%>

<% if @workshop.location %>
  <p>Location: <%=@workshop.location.name%></p>
  <p>Location: <%=@workshop.location.address%></p>
<% end %>

<% if @workshop.slot_id?%>
  <p>Time: <%=@workshop.slot.time%></p>
<% end %>

<% if current_user %>
  <%= link_to "Edit", edit_workshop_path(@workshop) %>
<% end %>